- name: Ping all hosts in the inventory
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping the hosts
      ansible.builtin.ping:
      ignore_errors: yes

    - name: Ping google from each host
      ansible.builtin.command: ping -c 4 google.com
      changed_when: false
      ignore_errors: yes

- name: Check if a website is reachable
  hosts: isprouter, remote_employee
  gather_facts: no
  tasks:
    - name: Check if the website is reachable
      ansible.builtin.uri:
        url: "http://172.30.0.10"
        return_content: no
        validate_certs: no
      ignore_errors: yes

- name: Check mariadb login
  hosts: isprouter
  become: yes
  gather_facts: no
  tasks:
    - name: Install mariadb, client and python connection library
      ansible.builtin.package:
        name:
          - mariadb
          - mariadb-client
          - py3-pymysql
        state: present

    - name: Check if we can log in to mariadb
      ansible.mariadb.mariadb_db:
        login_host: 172.30.0.15
        name: db_services
        login_user: toor
        login_password: summer
        state: present
      check_mode: yes
      ignore_errors: yes
